static: ../static
map: https://api-maps.yandex.ru/services/constructor/1.0/js/?um=constructor%3A6d48de29cf40fc18e8799a8d6f5f057e5d7c9f5536a885047585d195623a96a3&amp;width=787&amp;height=561&amp;lang=ru_RU&amp;scroll=true
text: aaa

theme: jekyll-theme-architect